services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./resources:/resources
      - ./logs:/logs
      - ./.env:/.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_SERVER_CHECK_ENABLE=True
      - OLLAMA_HEALTH_CHECK_ENABLE=True
    ports:
      - "8000:8000"
    command: ["python", "run.py", "--workers", "3", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 10s
